export const REASON_CODES = [
  "unauthorized",
  "forbidden",
  "not_found",
  "invalid_request",
  "invalid_target_kind",
  "invalid_message_kind",
  "payload_too_large",
  "endpoint_not_owned",
  "session_not_owned",
  "session_not_found",
  "session_closed",
  "inbound_disabled",
  "no_default_route",
  "offer_not_found",
  "offer_expired",
  "offer_revoked",
  "offer_audience_mismatch",
  "communication_session_not_active",
  "communication_session_expired",
  "communication_session_revoked",
  "communication_session_declined",
  "request_expired",
  "wrong_participant",
  "wrong_target",
  "message_expired",
  "delivery_terminal",
  "client_message_id_conflict",
  "ack_not_applicable",
  "queued_busy",
  "runtime_unavailable",
  "unsupported",
  "permission_required",
  "steer_not_allowed",
  "control_plane_unavailable",
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];
